"""Add user relationship to Reservation

Revision ID: b860da88cb8d
Revises: 821dcdcbf49c
Create Date: 2024-01-24 10:35:22.286705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b860da88cb8d'
down_revision = '821dcdcbf49c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
